### ISSUE TITLE
Merge Request with GemsEconomy

### ISSUE THREAD

**Issue by Ant4rez** [TheNewEconomy/Reserve#12]
This a economy plugin made by Xanium, it's supports multicurrency system so it will be cool see this with reserve api and not with vault.

https://gitlab.com/xanium-s-spigot-plugins/GemsEconomy

**Comment by creatorfromhell** [comment]
I made a ticket on it for now. https://gitlab.com/xanium-s-spigot-plugins/GemsEconomy/issues/3 If I get some free time I'll PR it over.
