### ISSUE TITLE
Need explanation about major and minor tiers of currency

### ISSUE THREAD

**Issue by wysohn** [TheNewEconomy/Reserve#14]
Based on implementation [here](https://github.com/TheNewEconomy/TNE-Bukkit/blob/7f40192acbae4bd2a04d3fadcf283a705adef6c0/TNE/src/net/tnemc/core/common/currency/TNECurrency.java#L209), it seems to be just returning null. 

Any plan on using it?

**Comment by creatorfromhell** [comment]
I'm not sure why I didn't implement it. But essentials a major tier is a whole value while a minor tier is a decimal value.

**Comment by wysohn** [comment]
Now that's interesting.

For just a clarification,

Can I think it as some kind of physical monetary entity?

For example, we provide TreeMap<Integer, Tier>,

Then the key is for the amount of currency, and value, the Tier, is the detailed information.

So dollar, for example, the major tiers would consist of a key, 100, 20, 10, 5, and 1, and minor tiers would consist of 25, 10, 5, 1, that each of them equivalent to 100, 20, 10, 5, and 1 dollar paper money, and 25, 10, 5, 1, that each of them equivalent to cents money.

---

For Tier, weight() will decided how much worth each tier would have.

100 major tier will worth 100.0

10 minor tier will worth 0.10

Correct me if I'm wrong

---

It could be also nice to open up Wiki section so anybody can edit it. Even if someone does something bad, it internally uses git as well, so you can always rollback if you want to.

**Comment by creatorfromhell** [comment]
> Now that's interesting.
> 
> For just a clarification,
> 
> Can I think it as some kind of physical monetary entity?
> 
> For example, we provide TreeMap<Integer, Tier>,
> 
> Then the key is for the amount of currency, and value, the Tier, is the detailed information.
> 
> So dollar, for example, the major tiers would consist of a key, 100, 20, 10, 5, and 1, and minor tiers would consist of 25, 10, 5, 1, that each of them equivalent to 100, 20, 10, 5, and 1 dollar paper money, and 25, 10, 5, 1, that each of them equivalent to cents money.
> 
> For Tier, weight() will decided how much worth each tier would have.
> 
> 100 major tier will worth 100.0
> 
> 10 minor tier will worth 0.10
> 
> Correct me if I'm wrong
> 
> It could be also nice to open up Wiki section so anybody can edit it. Even if someone does something bad, it internally uses git as well, so you can always rollback if you want to.

Yes, that's correct that 100 major tier = 100.0 and 10 minor = .10.

**Comment by creatorfromhell** [comment]
The wiki is now open to public editors.

**Comment by wysohn** [comment]
@creatorfromhell 
Apparently, it seems like there was a change in the Tier class

weight() method is int until 1.4.8 and is double in 1.5.0

Which one should I follow?

TNE doesn't work with 1.5.0 anyway, so I guess I have to stick with int for now
